#!/bin/bash

set -e
export DATAVERSE_SOURCE_DIR="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

(
  cd "${DATAVERSE_SOURCE_DIR}"

  export BUILD_VERSION="dv-1.1"
  export DATAVERSE_CONFIG_FILES=(
    "conf/glassfish/dataverse.properties"
    "conf/glassfish/default.config"
    "conf/glassfish/run-install.sh"
    "conf/prometheus/prometheus_exporter.yaml"
  )
  export DATAVERSE_LOCAL_WORKING_DIR="${DATAVERSE_SOURCE_DIR}/fairchive-dist/target/container"
  export DATAVERSE_CONTAINER_WORKING_DIR="/fairchive/fairchive-dist/target/container"
  export DATAVERSE_DIST_DIR="${DATAVERSE_SOURCE_DIR}/fairchive-dist/target/dist"
  export COMPOSE_CMD="docker compose -f dev.yml"

  cd "${DATAVERSE_SOURCE_DIR}/conf"

  usage() {
      echo "Usage: $(basename $0) [command]"
      echo "Commands: "
      echo " install                  Start and run the service installation"
      echo " destroy                  Destroy all the containers and volumes"
      echo " start                    Start all the services"
      echo " stop                     Stop the environment"
      echo " restart <service>        Restart the container of the given service"
      echo " logs <service>           Show container logs for the given service"
      echo " console <service>        Open a bash console inside the service container"
      echo " glassfish <command>      Run a command on the glassfish container"
      echo " -h|help"
      echo " -v|version]"
      echo
      echo "Services:"
      echo " postgres"
      echo " solr"
      echo " glassfish"
      echo " smtp"
      echo " keycloak"
      exit
  }

  usage_glassfish() {
      echo "Usage: $(basename $0) glassfish  [command] [-h|--help]"
      echo "Commands:"
      echo "  start                        Start glassfish"
      echo "  stop                         Stop glassfish"
      echo "  undeploy                     Undeploy fairchive WAR"
      echo "  deploy                       Deploy the fairchive WAR"
      echo "  redeploy                     Undeploy and deploy the fairchive WAR"
      echo "  apps                         Show the currently deployed applications"
      echo "  logging                      Show the currently set logging levels"
      echo "  set-logging <logger>=<level> Set the logging level for the provided logger (eg. org.apache.activemq=INFO)"
      echo "  asadmin <cmd>                Run glassfish asadmin command"
      echo " -h|help"
      exit
  }

  version() {
    echo "BUILD_VERSION: ${BUILD_VERSION}"
    echo "DATAVERSE_SOURCE_DIR: ${DATAVERSE_SOURCE_DIR}"
    echo "DATAVERSE_DIST_DIR: ${DATAVERSE_DIST_DIR}"
    echo "EXTENSION_SOURCE_DIR: ${EXTENSION_SOURCE_DIR}"
    echo "EXTENSION_DIST_DIR: ${EXTENSION_DIST_DIR}"
    echo "COMPOSE_CMD: ${COMPOSE_CMD}"
    echo "DATAVERSE_CONFIG_FILES: ${DATAVERSE_CONFIG_FILES[*]}"
  }


  install() {

    echo "* Starting dev environment services."
    ${COMPOSE_CMD} up -d

    echo "* Configuring dev environment."
    rm -rf "${DATAVERSE_LOCAL_WORKING_DIR}"
    mkdir -p "${DATAVERSE_LOCAL_WORKING_DIR}"

    echo "* Copying files."
    for i in "${!DATAVERSE_CONFIG_FILES[@]}"; do
      echo "* Copying ${DATAVERSE_CONFIG_FILES[$i]}"
      copy_to_dv_container_with_fallback "${EXTENSION_SOURCE_DIR}" "${DATAVERSE_SOURCE_DIR}" "${DATAVERSE_CONFIG_FILES[$i]}"
    done

    copy_to_dv_container_with_fallback "${EXTENSION_DIST_DIR}" "${DATAVERSE_DIST_DIR}" "*.war" "fairchive.war"
    copy_to_dv_container_with_fallback "${EXTENSION_DIST_DIR}" "${DATAVERSE_DIST_DIR}" "activemq"
    copy_to_dv_container_with_fallback "${EXTENSION_DIST_DIR}" "${DATAVERSE_DIST_DIR}" "glassfish"

    echo "* Running installation script inside the container."
    exec_script_in_dv_container "run-install.sh"

    if [[ $(type -t extension_post_install) == function ]]; then
      echo "* Extension post install."
      extension_post_install
    fi

    echo "* Stopping the environment"
    ${COMPOSE_CMD} stop
  }

  exec_script_in_dv_container() {
    SCRIPT_TO_EXECUTE="$1"
    ${COMPOSE_CMD} exec -T glassfish /bin/bash -c "${DATAVERSE_CONTAINER_WORKING_DIR}/${SCRIPT_TO_EXECUTE}"
  }

  asadmin() {
    ${COMPOSE_CMD} exec -T glassfish /usr/local/glassfish4/bin/asadmin "$@"
  }

  deploy() {
    mkdir -p ${DATAVERSE_LOCAL_WORKING_DIR}
    copy_to_dv_container_with_fallback "${EXTENSION_DIST_DIR}" "${DATAVERSE_DIST_DIR}" "*.war" "fairchive.war"
    asadmin deploy ${DATAVERSE_CONTAINER_WORKING_DIR}/fairchive.war
  }

  glassfish() {
    if [ $# -eq 0 ]; then
      usage_glassfish
      exit
    fi

    while [[ $# -gt 0 ]]
    do
      key="$1"
      case $key in
        start)
          shift
          asadmin start-domain --debug
          exit
          ;;
        stop)
          shift
          asadmin stop-domain
          exit
          ;;
        undeploy)
          shift
          asadmin undeploy fairchive
          exit
          ;;
        deploy)
          shift
          deploy
          exit
          ;;
        redeploy)
          shift
          asadmin undeploy fairchive
          deploy
          exit
          ;;
        apps)
          shift
          asadmin list-applications
          exit
          ;;
        logging)
          shift
          asadmin list-log-levels
          exit
          ;;
        set-logging)
          shift
          asadmin set-log-levels "$@"
          exit
          ;;
        asadmin)
          shift
          asadmin "$@"
          exit
          ;;
        -h|--help)
          usage_glassfish
          exit
          ;;
        *)
          usage_glassfish
          exit
          ;;
      esac
    done
  }

  copy_to_dv_container_with_fallback() {
    SRC_EXT_DIR="$1"
    SRC_DV_DIR="$2"
    SRC_FILE="$3"
    DEST="$4"

    SRC_EXT="${SRC_EXT_DIR}/${SRC_FILE}"
    SRC_DV="${SRC_DV_DIR}/${SRC_FILE}"

    copy_to_dv_container "${SRC_EXT}" "${DEST}" || \
      copy_to_dv_container "${SRC_DV}" "${DEST}" || \
      (echo "Could not copy ${SRC_FILE} from ${SRC_EXT_DIR} or ${SRC_DV_DIR}." && exit 1)
  }

  copy_to_dv_container() {
    SRC="$1"
    DEST="$2"
    DEST_FULL_PATH="${DATAVERSE_LOCAL_WORKING_DIR}/$DEST"

    if [[ -d ${SRC} ]]; then
        cp -ur "${SRC}" "${DEST_FULL_PATH}"
        true
    elif [[ -f ${SRC} ]]; then
        cp -u "${SRC}" "${DEST_FULL_PATH}"
        true
    elif compgen -G "${SRC}" > /dev/null; then
      for f in ${SRC}; do
        copy_to_dv_container "${f}" "${DEST}"
      done
    else
      false
    fi
  }

  if [ $# -eq 0 ]; then
    usage
    exit
  fi


  while [[ $# -gt 0 ]]
  do
    key="$1"
    case $key in
      install)
        shift
        install
        exit
        ;;
      destroy)
        shift
        ${COMPOSE_CMD} down --volumes
        exit
        ;;
      start)
        shift
        ${COMPOSE_CMD} up -d
        exit
        ;;
      stop)
        shift
        ${COMPOSE_CMD} stop
        exit
        ;;
      restart)
        shift
        ${COMPOSE_CMD} restart "$@"
        exit
        ;;
      logs)
        shift
        ${COMPOSE_CMD} logs -f "$@"
        exit
        ;;
      console)
        shift
        ${COMPOSE_CMD} exec "$@" /bin/bash
        exit
        ;;
      glassfish)
        shift
        glassfish "$@"
        exit
        ;;
      -h|--help)
        usage
        exit
        ;;
      -v|version)
        version
        exit
        ;;
      *)
        usage
        exit
        ;;
    esac
  done

)

